name: pulse_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_feather_icons: ^2.0.0+1
  flutter_secure_storage: ^9.2.4
  cached_network_image: ^3.2.1
  flutter_svg: ^2.1.0
  image_picker: ^1.1.2
  string_2_icon: ^0.0.2
  webview_flutter: ^4.11.0
  webview_flutter_android: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/doctor1.png
    - assets/doctor2.png
    - assets/doctor3.png
    - assets/logo_blue.png
    - assets/Google_Icon.webp
    - assets/Apple-Logo.png
    - assets/corporate_fare_600dp.png
    - assets/pill_600dp.png
    - assets/stethoscope_600dp.png
    - assets/cardiology_600dp.png
    - assets/accessibility_600dp.png
    - assets/child_friendly_600dp.png
    - assets/neurology_600dp_.png
    - assets/gastroenterology_600dp.png